# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7c3ab5ded2eb0321547ceb0c899df2cbd22eb1f17c157c9b211648186286575f36e9fdb5995eee78d3e55260114728140772b4309e66b8308631ffe53360d5

test:
  secret_key_base: e074f2d2fb7a868c851726255de5e6d8a339ad0adaac248adf1d0b8727f19a1e19068e3609b5faecdd7696577bb864761ef9a2ebd48af3212bd4f92cdf862d86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
